### ISSUE TITLE
Broken on Avalonia 0.10.19 and up

### ISSUE THREAD

**Issue by colejohnson66** [Nickelony/SpacedGrid.Avalonia#2]
Version 0.10.18.1 is broken on Avalonia 0.10.19 and up. Version 0.10.18 does not have an issue, and we used it instead. After spending some time tracking it down, I've deduced that, at least for Avalonia 0.10.21 (not 19), `(Row|Column)Definitions.CollectionChanged` never fires during initialization.

This is unconfirmed, but I guess Avalonia would previously do `(Row|Column)Definitions.Add` (which *would* fire the event during layout), but now they do `(Row|Column)Definitions = x` (which does *not* fire).

 I see in [the commit](https://github.com/Nickelony/AvaloniaSpacedGrid/commit/2634839f98bb450fd11d1e0a8993e8c0552aab3e) that you removed the `SpacedGrid.OnInitialized`. I manged to fix this by adding it *back* as such:

```cs
protected override void OnInitialized()
{
    // the "collection changed" events aren't called on initialization as the property is assigned directly, so we need
    //   to update them directly when we initialize
    base.OnInitialized();

    RowDefinitions.CollectionChanged += delegate { UpdateSpacedRows(); };
    ColumnDefinitions.CollectionChanged += delegate { UpdateSpacedColumns(); };

    UpdateSpacedRows();
    UpdateSpacedColumns();
}
```

**Comment by Nickelony** [comment]
I will take a look at it tomorrow, thanks for reporting and tracking down the issue! :)

**Comment by Nickelony** [comment]
@colejohnson66 I couldn't replicate any issues on my end, could you please show me an example .axaml snippet where it definitely doesn't work? I used the Demo project I provided and updating Avalonia didn't seem to change anything.
If that doesn't do it, I could use the `OnInitialized()` solution you suggested, since I guess it's more future-proof.
It would also be nice if you said what exactly doesn't work? Do the items get placed into the wrong rows / columns or does the spacing not work at all?

**Comment by colejohnson66** [comment]
Weird that you can't reproduce it. We got it consistently on our internal tools we were using it on, and it only manifested on 0.10.18.1; Never on 0.10.18.

All I know is two things: (1) The grid's children _did_ have `Grid.(Row|Column)(Span)` updated to accommodate the spacers, but the grid itself did _not_ have `(Row|Column)Definitions` updated. If I manually, using Avalonia's dev tools (F12), updated `(Row|Column)Definitions`, the layout looked fine. This is because: (2) `UpdatedSpaced(Rows|Columns)` never ran. I placed a breakpoint in them, and they never hit.

I'll see about getting something reproducible this next week.

**Comment by Nickelony** [comment]
@colejohnson66 Any updates for something I can use to replicate the issue?
