### ISSUE TITLE
Is the Avalonia preview version unusable?

### ISSUE THREAD

**Issue by pyking-wang** [Nickelony/SpacedGrid.Avalonia#3]
error：Could not load type 'Avalonia.Controls.IControl' from assembly 'Avalonia.Controls, Version=11.0.999.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'.
Hello，can Avalonia11 be used?

**Comment by Nickelony** [comment]
Seems like Avalonia has done some breaking changes to their classes. `IControl` has been replaced with `Control`. I will push a fix this week, thanks for reporting! :)

**Comment by Nickelony** [comment]
Fixed, please update your NuGet package :)

**Comment by pyking-wang** [comment]
I will give it a try, thank you :)
